import { StyleSheet } from 'react-native-unistyles'

export const styles = StyleSheet.create((theme) => ({
  item: {
    width: '100%',
    backgroundColor: theme.colors.palette.item_alpha_92,
    padding: theme.size.s14,
    borderRadius: theme.size.s24,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.border,
    overflow: 'hidden',
    variants: {
      isDeleteActive: {
        true: {
          backgroundColor: theme.colors.palette.red_opacity_1,
        },
      },
    },
  },
  glowOrb: {
    position: 'absolute',
    top: -theme.size.s36,
    right: -theme.size.s18,
    width: theme.size.s96,
    height: theme.size.s96,
    borderRadius: theme.size.s96 / 2,
    backgroundColor: theme.colors.palette.success_alpha_16,
  },
  header: {
    width: '100%',
    marginBottom: theme.size.s12,
    gap: theme.size.s10,
  },
  headerMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: theme.size.s10,
  },
  metaGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.size.s8,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.size.s10,
    paddingVertical: theme.size.s7,
    borderRadius: theme.size.s999,
    backgroundColor: theme.colors.palette.bg_modal_light,
  },
  status: {
    width: theme.size.s12,
    height: theme.size.s12,
    borderRadius: theme.size.s12 / 2,
    variants: {
      statusTone: {
        study: {
          backgroundColor: theme.colors.palette.item_study,
        },
        ready: {
          backgroundColor: theme.colors.palette.item_ready,
        },
      },
    },
  },
  statusBadgeText: {
    marginLeft: theme.size.s6,
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.white,
    fontFamily: theme.fonts.bold,
    textTransform: 'uppercase',
    letterSpacing: theme.letterSpacing.s08,
  },
  wordsBadge: {
    paddingHorizontal: theme.size.s10,
    paddingVertical: theme.size.s7,
    borderRadius: theme.size.s999,
    backgroundColor: theme.colors.palette.white_alpha_05,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.white_alpha_06,
  },
  wordsBadgeText: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.gray_text,
    fontFamily: theme.fonts.bold,
  },
  flagWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: theme.size.s30,
    height: theme.size.s30,
    borderRadius: theme.size.s999,
    //backgroundColor: theme.colors.palette.white_alpha_05,
    backgroundColor: 'red',
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.white_alpha_06,
  },
  flag: {
    width: theme.size.s20,
    height: theme.size.s20,
    borderRadius: theme.size.s20 / 2,
    resizeMode: 'cover',
  },

  date: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.gray_text,
    fontFamily: theme.fonts.bold,
  },

  content: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    justifyContent: 'space-between',
    gap: theme.size.s12,
  },
  translateAction: {
    position: 'relative',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  btnTranslate: {
    alignItems: 'center',
    justifyContent: 'center',
    width: theme.size.s50,
    height: theme.size.s50,
    gap: theme.size.s6,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.palette.surface_light,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.success_alpha_22,
    zIndex: 1,
  },
  translateGlow: {
    position: 'absolute',
    top: theme.size.s4,
    right: theme.size.s6,
    left: theme.size.s6,
    bottom: theme.size.s4,
    borderRadius: theme.size.s18,
    backgroundColor: theme.colors.palette.success_alpha_16,
  },

  tapHint: {
    marginTop: theme.size.s10,
    paddingVertical: theme.size.s10,
    paddingHorizontal: theme.size.s12,
    borderRadius: theme.size.s16,
    backgroundColor: theme.colors.palette.success_alpha_12,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.success_alpha_22,
  },
  tapHintText: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.white,
    fontFamily: theme.fonts.bold,
  },
  descriptionBlock: {
    marginTop: theme.size.s10,
    borderTopWidth: theme.size.s1,
    borderTopColor: theme.colors.palette.border,
    paddingTop: theme.size.s10,
  },
  description: {
    fontSize: theme.fontSize.s14,
    color: theme.colors.palette.gray_text,
  },
  showFooterBtn: {
    width: '100%',
    flexDirection: 'row',
    paddingVertical: theme.size.s10,
    marginTop: theme.size.s10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.size.s8,
    backgroundColor: theme.colors.palette.bg_modal_light,
    borderRadius: theme.size.s14,
  },
  showFooterText: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.gray_text,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.bold,
    letterSpacing: theme.letterSpacing.s08,
  },
  statusText: {
    fontSize: theme.fontSize.s14,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.bold,
    variants: {
      statusTone: {
        study: {
          color: theme.colors.palette.item_study,
        },
        ready: {
          color: theme.colors.palette.item_ready,
        },
      },
    },
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
    marginTop: theme.size.s12,
    gap: theme.size.s8,
  },
  footerAction: {
    flex: 1,
    minHeight: theme.size.s42,
    paddingHorizontal: theme.size.s8,
    borderRadius: theme.size.s16,
    backgroundColor: theme.colors.palette.white_alpha_03,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.white_alpha_06,
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.size.s4,
  },
  footerActionText: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.white,
    fontFamily: theme.fonts.bold,
  },
  footerDeleteText: {
    fontSize: theme.fontSize.s12,
    color: theme.colors.palette.red,
    fontFamily: theme.fonts.bold,
  },
}))
