import { StyleSheet } from 'react-native-unistyles'

export const styles = StyleSheet.create((theme) => ({
  title: {
    fontSize: theme.fontSize.s14,
    marginBottom: theme.size.s8,
    color: theme.colors.palette.gray_text,
  },
  dropdownWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  dropdown: {
    minHeight: theme.size.s56,
    backgroundColor: theme.colors.palette.surface,
    borderRadius: theme.size.s16,
    paddingHorizontal: theme.size.s8,
    paddingVertical: theme.size.s14,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.border,
  },
  containerStyle: {
    backgroundColor: theme.colors.palette.surface_light,
    borderRadius: theme.size.s24,
    marginTop: theme.size.s8,
    borderColor: theme.colors.palette.border,
    maxHeight: '80%',
    overflow: 'hidden',
    padding: theme.size.s8,
  },
  placeholderStyle: {
    fontSize: theme.fontSize.s16,
    color: theme.colors.palette.dark_placeholder,
  },
  selectedTextStyle: {
    fontSize: theme.fontSize.s16,
    color: theme.colors.palette.white,
    lineHeight: theme.lineHeights.md,
  },
  selectedTextStyleActive: {
    color: theme.colors.palette.black,
  },
  inputSearchStyle: {
    height: theme.size.s48,
    fontSize: theme.fontSize.s16,
    lineHeight: theme.lineHeights.md,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.border,
    borderRadius: theme.size.s14,
    color: theme.colors.palette.white,
    backgroundColor: theme.colors.palette.surface,
    paddingHorizontal: theme.size.s14,
    marginBottom: theme.size.s10,
  },
  iconStyle: {
    width: theme.size.s20,
    height: theme.size.s20,
  },
  item: {
    padding: theme.size.s12,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: theme.size.s14,
    borderWidth: 0,
    marginBottom: theme.size.s6,
  },
  itemContainer: {
    borderRadius: theme.size.s14,
    overflow: 'hidden',
    borderWidth: 0,
  },
  itemActive: {
    backgroundColor: theme.colors.palette.primery,
    borderWidth: 0,
  },
  label: {
    fontSize: theme.fontSize.s16,
    color: theme.colors.palette.white,
  },
  optionContainer: {
    position: 'absolute',
    zIndex: 100,
    top: theme.size.s60,
    left: theme.size.s0,
    backgroundColor: theme.colors.palette.dark_placeholder,
    width: '100%',
    borderBottomLeftRadius: theme.size.s10,
    borderBottomRightRadius: theme.size.s10,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.dark_placeholder,
  },
  selectItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon: {
    width: theme.size.s15,
    height: theme.size.s15,
    borderRadius: theme.size.s15 / 2,
    resizeMode: 'contain',
    marginRight: theme.size.s5,
  },
  selectedStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    minHeight: theme.size.s30,
    borderRadius: theme.size.s14,
    backgroundColor: theme.colors.palette.surface_light,
    borderWidth: theme.size.s1,
    borderColor: theme.colors.palette.border,
    marginRight: theme.size.s8,
    padding: theme.size.s6,
  },
  selectedRow: {
    position: 'absolute',
    left: theme.size.s8,
    right: theme.size.s36,
    top: theme.size.s8,
    bottom: theme.size.s8,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  textSelectedStyle: {
    fontSize: theme.fontSize.s16,
    color: theme.colors.palette.white,
    lineHeight: theme.lineHeights.md,
  },
}))
